INSERT INTO DEPARTAMENTO (ID,NOMBRE) VALUES (2,'QUICHE');
INSERT INTO DEPARTAMENTO (ID,NOMBRE) VALUES (1,'HUEHUETENANGO');
INSERT INTO DEPARTAMENTO (ID,NOMBRE) VALUES (3,'SAN MARCOS');
INSERT INTO DEPARTAMENTO (ID,NOMBRE) VALUES (4,'SOLOLA');
INSERT INTO DEPARTAMENTO (ID,NOMBRE) VALUES (5,'TOTONICAPAN');
