INSERT INTO ESTADO_CONYUGAL (ID,NOMBRE) VALUES (2,'Unido');
INSERT INTO ESTADO_CONYUGAL (ID,NOMBRE) VALUES (1,'Soltero(a)');
INSERT INTO ESTADO_CONYUGAL (ID,NOMBRE) VALUES (3,'Separado(a) de union');
INSERT INTO ESTADO_CONYUGAL (ID,NOMBRE) VALUES (4,'Separado(a) de matrimonio');
INSERT INTO ESTADO_CONYUGAL (ID,NOMBRE) VALUES (5,'Viudo(a)');
INSERT INTO ESTADO_CONYUGAL (ID,NOMBRE) VALUES (6,'Casado');
INSERT INTO ESTADO_CONYUGAL (ID,NOMBRE) VALUES (7,'Menor de edad');
