INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (2,'Akateko');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (1,'Kiche');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (3,'No indigena');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (4,'Mam');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (5,'Tzutujil');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (6,'Jacalteco');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (7,'Kaqchikel');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (8,'Qanjobal');
INSERT INTO GRUPO_ETNICO (ID,NOMBRE) VALUES (9,'Chuj');
